### PR TITLE
expose type definitions file and sourcemaps

### LINKED ISSUE #13: TypeScript Definitions Not Included in Package
Hey all!

Thanks for forking minimist, it's nice to see work being done on an abandoned project once more. I pulled this project into my application and noticed TypeScript was complaining saying `Could not find a declaration file for module 'minimist-lite'.` I saw that you have an `index.d.ts` in the repo and looked in the package itself to investigate. To my surprise, I saw that the `d.ts` wasn't included with the packaged module (see the attached screenshot for details)

Screen Shot 2022-01-23 at 2 36 58 PM

As a workaround I've created an empty `minimist-lite.d.ts` with the contents `declare module 'minimist-lite';`, but I know this isn't a sustainable route to take moving forward

### PR DESCRIPTION
**Pull request by micalevisk**
closes #13

### CODE REVIEW

**Comment by micalevisk** [comment]
@meszaros-lajos-gyorgy I notice that we don't have source maps, which can make things hard to debug. Is it on purpose (to make the bundle size smaller I guess)?

`npm pack` here with source maps outputs `unpacked size: 34.6 kB`  
without them: `unpacked size: 15.8 kB`

**Comment by meszaros-lajos-gyorgy** [comment]
the new gitignore seems to be a bit too general for me, but at least once that's in the codebase it never-ever has to be touched again, so I can live with it. :)

About sourcemaps, esbuild was just recently introduced to the repo and I'm just learning on how it can be managed, but yes, we can add another config option to the command to produce sourcemaps too, it's just a matter of adding `--sourcemap` to the command. Could you add that to this PR too, please?

**Comment by micalevisk** [comment]
@meszaros-lajos-gyorgy done! I like the ideia of keeping the package size small. I'm not sure if could gain something by using `esbuild` as the size of sourcemap+bundle is bigger then having only the source code

I know that with esbuild we could [publish both ESM and CJS](https://antfu.me/posts/publish-esm-and-cjs#context-misalginment)

**Comment by micalevisk** [comment]
also, I don't think we need to track on git the generated file (`index.js` on root) on the repo. What do you think?

you just need to build & publish locally instead

**Comment by meszaros-lajos-gyorgy** [comment]
Good point, the generated index.js can be removed from git as it will always change whenever the sources change! Please open a ticket for the topic of CI/CD and we can continue the discussion there.

**Comment by meszaros-lajos-gyorgy** [comment]
We already have a ticket on that, if forgot... :D

**Pull request merged**
