### PR TITLE
ci: add 'continuous integration' & 'publish' github workflows

### LINKED ISSUE #15: Automate publishing on NPM registry using GitHub Actions. And add CI workflow
Currently only you (I guess) can release new versions of this package.

We could use GitHub actions to automatically publish new versions to NPM registry after some event on this repo.

My proposal: publish on new releases on this repo.  
An example of an workflow that publish the package on new Git Tags (that could be easily adapted): https://github.com/micalevisk/nestjs-swagger-api-http-response-decorators/blob/main/.github/workflows/publish-on-new-tag.yml

You just need to add a [secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets) called `NPM_TOKEN` with your [NPM access token](https://docs.npmjs.com/creating-and-viewing-access-tokens) into this repo.

---

Also, to make thinks more safer, we can add another CI workflow that will be triggered on every PR that change some code. It will ran automated tests & coverage report. So we'll make sure that only good PRs are merged to the main branch.

---

To implement this, I need to know a bit more about how is the current workflow from changing the code til release a new version.

### PR DESCRIPTION
**Pull request by micalevisk**
closes #15 

I've added one workflow to run tests and another to just publish. Is it fine? 

---

Also, the `ci.yml` will fail for now because `npm run test` exits with non-zero code due to code coverage report constraints, and I don't believe we should relax that. 

image
 
image

image

image

### CODE REVIEW

**Comment by micalevisk** [comment]
btw @meszaros-lajos-gyorgy what's the reason the following is nested under a try-catch clause? will `Number(x)` or `Number.MAX_SAFE_INTEGER` raise an error in some case?

https://github.com/meszaros-lajos-gyorgy/minimist-lite/blob/50bfec5cd161af8499a51a6ebfcf3ef3e0889a69/src/functions.js#L4-L8

**Review by meszaros-lajos-gyorgy — APPROVED** [review]
Very well done! Thank you ever so much on researching this!

**Comment by meszaros-lajos-gyorgy** [comment]
Hi! Sorry for the late respone, had a busy week.
Let's have a test run, I'm curious to see if this works properly.

**Comment by meszaros-lajos-gyorgy** [comment]
I think we should introduce a development branch so that we can have a controlled release procedure and not release a new version on every commit. What do you say?

**Comment by micalevisk** [comment]
the release workflow is triggered by new git tags starting with `v`, isn't this good?

**Comment by meszaros-lajos-gyorgy** [comment]
> btw @meszaros-lajos-gyorgy what's the reason the following is nested under a try-catch clause? will `Number(x)` or `Number.MAX_SAFE_INTEGER` raise an error in some case?
> 
> https://github.com/meszaros-lajos-gyorgy/minimist-lite/blob/50bfec5cd161af8499a51a6ebfcf3ef3e0889a69/src/functions.js#L4-L8

I have no idea why this is in a try catch cause, it was probably refactored back then from a code, which threw an error upon parsing a number. I think it can be removed, but let me double check that number constructor.

**Comment by meszaros-lajos-gyorgy** [comment]
> the release workflow is triggered by new git tags starting with `v`, isn't this good?

Ah, okay, that is perfect!

**Comment by micalevisk** [comment]
sure. Then you can open a PR to test the CI workflow

The issue is that the code coverage isn't 100% so it will fail

**Comment by meszaros-lajos-gyorgy** [comment]
Checked the Number constructor and nowhere does it mentions that it might throw an error: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/Number
Parsing something, which is not a number will result in NaN, which can be compared with numbers without throwing an error.

**Comment by meszaros-lajos-gyorgy** [comment]
I think I never saw the coverage report being 100% before and I would be perfectly happy with around 90% check, but if you say that we should aim for 100% then I can support that too.

**Comment by micalevisk** [comment]
@meszaros-lajos-gyorgy what about

```json
  "tap": {
    "branches": 95,
    "lines": 80,
    "functions": 100,
    "statements": 80
  },
```

you can try it locally by adding the above in your `package.json`, and run `npm t`

**Comment by meszaros-lajos-gyorgy** [comment]
Let's go with this!

**Comment by micalevisk** [comment]
would you like to made that change along with the refactoring of that `isNumber` func? it would be even better if you manage improve the code coverage threshold

Also, I think is better to move the tap config above to a new `.taprc` file (it's a JSON file).

**Comment by meszaros-lajos-gyorgy** [comment]
We should have a separate ticket for all of these small changes. Yes, I can implement these changes.

**Pull request merged**
